// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9mu4RO3j6TAUMGgoZdoEWbTp4igP4LFY',
    appId: '1:991942880159:web:d013d1707801eb7d1dabaa',
    messagingSenderId: '991942880159',
    projectId: 'warehousebd-3fa6b',
    authDomain: 'warehousebd-3fa6b.firebaseapp.com',
    storageBucket: 'warehousebd-3fa6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvxxiagyX3L7_dzW_AEX7X2RSHAvyzPCY',
    appId: '1:991942880159:android:f9e6c8a33cd3680f1dabaa',
    messagingSenderId: '991942880159',
    projectId: 'warehousebd-3fa6b',
    storageBucket: 'warehousebd-3fa6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtIxuqBxm1W3AwKmE8irgM2spk0tuDLb4',
    appId: '1:991942880159:ios:e206a8a090d0f0461dabaa',
    messagingSenderId: '991942880159',
    projectId: 'warehousebd-3fa6b',
    storageBucket: 'warehousebd-3fa6b.appspot.com',
    iosBundleId: 'com.example.mnm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtIxuqBxm1W3AwKmE8irgM2spk0tuDLb4',
    appId: '1:991942880159:ios:8f5231085faba0351dabaa',
    messagingSenderId: '991942880159',
    projectId: 'warehousebd-3fa6b',
    storageBucket: 'warehousebd-3fa6b.appspot.com',
    iosBundleId: 'com.example.mnm.RunnerTests',
  );
}
